// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jaxyvoaaswingqrcouvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpheHl2b2Fhc3dpbmdxcmNvdXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODg1NDEsImV4cCI6MjA3MDI2NDU0MX0.r7_YfrtZWAdC2xFB201uWwqePEn0GwvQWIdZCWFEufI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});